server:
  port: 8080

spring:
  application:
    name: stanchart-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.http.client.HttpClientAutoConfiguration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false
        use_sql_comments: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: OFF
    com.duncodi.ppslink.stanchart: DEBUG
    org.apache.http: DEBUG
    javax.net.ssl: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://service-discovery:8080/eureka}

admin:
  service:
    url: http://api-gateway:8080/admin/api/v1

# SCB Configuration - Using PEM private key for JWT and JKS for SSL
scb:
  ssl:
    keystore:
      path: ${STANCHART_KEYSTORE_PATH:/etc/ppslinkkeys/StanChartKeys/scbapibanking.jks}
      password: ${STANCHART_KEYSTORE_PASSWORD:PPSL1nk2025}
      type: JKS
  jwt:
    private-key:
      path: ${STANCHART_PRIVATE_KEY_PATH:/etc/ppslinkkeys/StanChartKeys/scbapibankingprivatekey.pem}